from __future__ import annotations

from typing import Protocol

from app.domain.models import Contestant, EpisodeStat, Roster, Season


class Store(Protocol):
    """All persistence the app needs. One interface, two implementations.

    Methods are synchronous: Lambda handles one request at a time and boto3
    is synchronous, so async buys nothing here yet.
    """

    # Seasons
    def list_seasons(self) -> list[Season]: ...
    def get_season(self, season_id: str) -> Season | None: ...
    def put_season(self, season: Season) -> None: ...

    # Contestants
    def list_contestants(self, season_id: str) -> list[Contestant]: ...
    def get_contestant(self, season_id: str, contestant_id: str) -> Contestant | None: ...
    def put_contestant(self, contestant: Contestant) -> None: ...

    # Episode stats
    def list_episode_stats(
        self, season_id: str, episode: int | None = None
    ) -> list[EpisodeStat]: ...
    def put_episode_stat(self, stat: EpisodeStat) -> None: ...

    # Rosters
    def list_rosters(self, season_id: str) -> list[Roster]: ...
    def get_roster(self, season_id: str, user_id: str) -> Roster | None: ...
    def put_roster(self, roster: Roster) -> None: ...
