from __future__ import annotations

from typing import Protocol

from app.domain.models import Contestant, EpisodeStat, League, LeagueMember, Season


class Store(Protocol):
    """All persistence the app needs. One interface, two implementations.

    Methods are synchronous: Lambda handles one request at a time and boto3
    is synchronous, so async buys nothing here yet.
    """

    # Seasons
    def list_seasons(self) -> list[Season]: ...
    def get_season(self, season_id: str) -> Season | None: ...
    def put_season(self, season: Season) -> None: ...

    # Contestants
    def list_contestants(self, season_id: str) -> list[Contestant]: ...
    def get_contestant(self, season_id: str, contestant_id: str) -> Contestant | None: ...
    def put_contestant(self, contestant: Contestant) -> None: ...

    # Episode stats
    def list_episode_stats(
        self, season_id: str, episode: int | None = None
    ) -> list[EpisodeStat]: ...
    def put_episode_stat(self, stat: EpisodeStat) -> None: ...

    # Leagues
    def get_league(self, league_id: str) -> League | None: ...
    def put_league(self, league: League) -> None: ...

    # Members (a member's roster lives on the member record)
    def list_members(self, league_id: str) -> list[LeagueMember]: ...
    def get_member(self, league_id: str, user_id: str) -> LeagueMember | None: ...
    def put_member(self, member: LeagueMember) -> None: ...
    def list_league_ids_for_user(self, user_id: str) -> list[str]: ...
