/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scoring-rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Scoring Rules */
    get: operations["scoring_rules_scoring_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Seasons */
    get: operations["list_seasons_seasons_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Season */
    get: operations["get_season_seasons__season_id__get"];
    /** Upsert Season */
    put: operations["upsert_season_seasons__season_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/contestants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Contestants */
    get: operations["list_contestants_seasons__season_id__contestants_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/contestants/{contestant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Upsert Contestant */
    put: operations["upsert_contestant_seasons__season_id__contestants__contestant_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/episodes/{episode}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Episode Stats */
    get: operations["list_episode_stats_seasons__season_id__episodes__episode__stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/episodes/{episode}/stats/{contestant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Record Stat */
    put: operations["record_stat_seasons__season_id__episodes__episode__stats__contestant_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/leaderboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Leaderboard */
    get: operations["get_leaderboard_seasons__season_id__leaderboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Contestant Points
     * @description Total points per contestant so far this season.
     */
    get: operations["contestant_points_seasons__season_id__points_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/rosters/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get My Roster */
    get: operations["get_my_roster_seasons__season_id__rosters_me_get"];
    /** Set My Roster */
    put: operations["set_my_roster_seasons__season_id__rosters_me_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Season Stats */
    get: operations["list_season_stats_seasons__season_id__stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Contestant */
    Contestant: {
      /** Eliminated Episode */
      eliminated_episode?: number | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Season Id */
      season_id: string;
      /** @default active */
      status: components["schemas"]["ContestantStatus"];
      /** Tribe */
      tribe?: string | null;
    };
    /** ContestantIn */
    ContestantIn: {
      /** Eliminated Episode */
      eliminated_episode?: number | null;
      /** Name */
      name: string;
      /** @default active */
      status: components["schemas"]["ContestantStatus"];
      /** Tribe */
      tribe?: string | null;
    };
    /** ContestantPointsOut */
    ContestantPointsOut: {
      /** Points */
      points: {
        [key: string]: number;
      };
    };
    /**
     * ContestantStatus
     * @enum {string}
     */
    ContestantStatus: "active" | "eliminated";
    /**
     * EpisodeStat
     * @description Event counts for one contestant in one episode. One record per pair.
     */
    EpisodeStat: {
      /** Contestant Id */
      contestant_id: string;
      /** Episode */
      episode: number;
      /** Events */
      events?: {
        [key: string]: number;
      };
      /** Season Id */
      season_id: string;
    };
    /** EpisodeStatIn */
    EpisodeStatIn: {
      /** Events */
      events?: {
        [key: string]: number;
      };
    };
    /**
     * EventType
     * @description Things that happen to a castaway in an episode and earn (or cost) points.
     * @enum {string}
     */
    EventType:
      | "survived_episode"
      | "individual_immunity"
      | "team_immunity"
      | "individual_reward"
      | "team_reward"
      | "idol_found"
      | "idol_played_successfully"
      | "advantage_found"
      | "correct_vote"
      | "vote_received"
      | "fire_making_win"
      | "voted_out"
      | "quit_or_medevac"
      | "final_three"
      | "jury_vote_received"
      | "sole_survivor";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Env */
      env: string;
      /** Status */
      status: string;
    };
    /** LeaderboardEntryOut */
    LeaderboardEntryOut: {
      /** Contestant Points */
      contestant_points: {
        [key: string]: number;
      };
      /** Display Name */
      display_name: string;
      /** Points */
      points: number;
      /** Rank */
      rank: number;
      /** User Id */
      user_id: string;
    };
    /** MeResponse */
    MeResponse: {
      /** Email */
      email: string | null;
      /** Permissions */
      permissions: string[];
      /** Sub */
      sub: string;
    };
    /**
     * Roster
     * @description A player's picks for a season. One roster per user per season.
     */
    Roster: {
      /** Contestant Ids */
      contestant_ids: string[];
      /** Display Name */
      display_name: string;
      /** Season Id */
      season_id: string;
      /** User Id */
      user_id: string;
    };
    /** RosterIn */
    RosterIn: {
      /** Contestant Ids */
      contestant_ids: string[];
      /** Display Name */
      display_name: string;
    };
    /** ScoringRulesOut */
    ScoringRulesOut: {
      /** Points */
      points: {
        [key: string]: number;
      };
    };
    /** Season */
    Season: {
      /**
       * Draft Open
       * @default true
       */
      draft_open: boolean;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Number */
      number: number;
      /**
       * Roster Size
       * @default 3
       */
      roster_size: number;
    };
    /** SeasonIn */
    SeasonIn: {
      /**
       * Draft Open
       * @default true
       */
      draft_open: boolean;
      /** Name */
      name: string;
      /** Number */
      number: number;
      /**
       * Roster Size
       * @default 3
       */
      roster_size: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  me_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  scoring_rules_scoring_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScoringRulesOut"];
        };
      };
    };
  };
  list_seasons_seasons_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"][];
        };
      };
    };
  };
  get_season_seasons__season_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upsert_season_seasons__season_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SeasonIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_contestants_seasons__season_id__contestants_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contestant"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upsert_contestant_seasons__season_id__contestants__contestant_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        contestant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContestantIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contestant"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_episode_stats_seasons__season_id__episodes__episode__stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        episode: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  record_stat_seasons__season_id__episodes__episode__stats__contestant_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        episode: number;
        contestant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EpisodeStatIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_leaderboard_seasons__season_id__leaderboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeaderboardEntryOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  contestant_points_seasons__season_id__points_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContestantPointsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_my_roster_seasons__season_id__rosters_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Roster"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_my_roster_seasons__season_id__rosters_me_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RosterIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Roster"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_season_stats_seasons__season_id__stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
