/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Leagues */
    get: operations["my_leagues_leagues_get"];
    put?: never;
    /** Create League */
    post: operations["create_league_leagues_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get League */
    get: operations["get_league_leagues__league_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update League */
    patch: operations["update_league_leagues__league_id__patch"];
    trace?: never;
  };
  "/leagues/{league_id}/leaderboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Leaderboard */
    get: operations["get_leaderboard_leagues__league_id__leaderboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_leagues__league_id__members_get"];
    put?: never;
    /** Join League */
    post: operations["join_league_leagues__league_id__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/members/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Membership */
    get: operations["my_membership_leagues__league_id__members_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/members/me/roster": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set My Roster */
    put: operations["set_my_roster_leagues__league_id__members_me_roster_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/scoring-rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** League Scoring Rules */
    get: operations["league_scoring_rules_leagues__league_id__scoring_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scoring-rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Scoring Rules */
    get: operations["scoring_rules_scoring_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Seasons */
    get: operations["list_seasons_seasons_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Season */
    get: operations["get_season_seasons__season_id__get"];
    /** Upsert Season */
    put: operations["upsert_season_seasons__season_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/contestants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Contestants */
    get: operations["list_contestants_seasons__season_id__contestants_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/contestants/{contestant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Upsert Contestant */
    put: operations["upsert_contestant_seasons__season_id__contestants__contestant_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/episodes/{episode}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Episode Stats */
    get: operations["list_episode_stats_seasons__season_id__episodes__episode__stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/episodes/{episode}/stats/{contestant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Record Stat */
    put: operations["record_stat_seasons__season_id__episodes__episode__stats__contestant_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Contestant Points
     * @description Points per contestant under the default rules (the shared, canonical view).
     */
    get: operations["contestant_points_seasons__season_id__points_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/seasons/{season_id}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Season Stats */
    get: operations["list_season_stats_seasons__season_id__stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Contestant */
    Contestant: {
      /** Eliminated Episode */
      eliminated_episode?: number | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Season Id */
      season_id: string;
      /** @default active */
      status?: components["schemas"]["ContestantStatus"];
      /** Tribe */
      tribe?: string | null;
    };
    /** ContestantIn */
    ContestantIn: {
      /** Eliminated Episode */
      eliminated_episode?: number | null;
      /** Name */
      name: string;
      /** @default active */
      status?: components["schemas"]["ContestantStatus"];
      /** Tribe */
      tribe?: string | null;
    };
    /** ContestantPointsOut */
    ContestantPointsOut: {
      /** Points */
      points: {
        [key: string]: number;
      };
    };
    /**
     * ContestantStatus
     * @enum {string}
     */
    ContestantStatus: "active" | "eliminated";
    /**
     * EpisodeStat
     * @description Event counts for one contestant in one episode. One record per pair.
     */
    EpisodeStat: {
      /** Contestant Id */
      contestant_id: string;
      /** Episode */
      episode: number;
      /** Events */
      events?: {
        [key: string]: number;
      };
      /** Season Id */
      season_id: string;
    };
    /** EpisodeStatIn */
    EpisodeStatIn: {
      /** Events */
      events?: {
        [key: string]: number;
      };
    };
    /** ErrorOut */
    ErrorOut: {
      /** Detail */
      detail: string;
    };
    /**
     * EventType
     * @description Things that happen to a castaway in an episode and earn (or cost) points.
     * @enum {string}
     */
    EventType:
      | "survived_episode"
      | "individual_immunity"
      | "team_immunity"
      | "individual_reward"
      | "team_reward"
      | "idol_found"
      | "idol_played_successfully"
      | "advantage_found"
      | "correct_vote"
      | "vote_received"
      | "fire_making_win"
      | "voted_out"
      | "quit_or_medevac"
      | "final_three"
      | "jury_vote_received"
      | "sole_survivor";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Env */
      env: string;
      /** Status */
      status: string;
    };
    /** JoinLeagueIn */
    JoinLeagueIn: {
      /** Display Name */
      display_name: string;
      /** Join Code */
      join_code: string;
    };
    /** LeaderboardEntryOut */
    LeaderboardEntryOut: {
      /** Contestant Points */
      contestant_points: {
        [key: string]: number;
      };
      /** Display Name */
      display_name: string;
      /** Points */
      points: number;
      /** Rank */
      rank: number;
      /** User Id */
      user_id: string;
    };
    /** LeagueCreateIn */
    LeagueCreateIn: {
      /**
       * Display Name
       * @description Owner's name in the league
       */
      display_name: string;
      /** Name */
      name: string;
      /**
       * Roster Size
       * @default 3
       */
      roster_size?: number;
      /** Scoring Overrides */
      scoring_overrides?: {
        [key: string]: number;
      };
      /** Season Id */
      season_id: string;
    };
    /**
     * LeagueMember
     * @description One user's seat in a league: identity plus their roster.
     */
    LeagueMember: {
      /**
       * Contestant Ids
       * @default []
       */
      contestant_ids?: string[];
      /** Display Name */
      display_name: string;
      /** League Id */
      league_id: string;
      /** User Id */
      user_id: string;
    };
    /**
     * LeagueOut
     * @description A league as members see it. The join code is only shown to the owner.
     */
    LeagueOut: {
      /** Draft Open */
      draft_open: boolean;
      /** Id */
      id: string;
      /** Is Owner */
      is_owner: boolean;
      /** Join Code */
      join_code?: string | null;
      /** Name */
      name: string;
      /** Owner Id */
      owner_id: string;
      /** Roster Size */
      roster_size: number;
      /** Scoring Overrides */
      scoring_overrides: {
        [key: string]: number;
      };
      /** Season Id */
      season_id: string;
    };
    /** LeagueUpdateIn */
    LeagueUpdateIn: {
      /** Draft Open */
      draft_open?: boolean | null;
      /** Name */
      name?: string | null;
      /** Roster Size */
      roster_size?: number | null;
      /** Scoring Overrides */
      scoring_overrides?: {
        [key: string]: number;
      } | null;
    };
    /** MeResponse */
    MeResponse: {
      /** Email */
      email: string | null;
      /** Permissions */
      permissions: string[];
      /** Sub */
      sub: string;
    };
    /** RosterIn */
    RosterIn: {
      /** Contestant Ids */
      contestant_ids: string[];
    };
    /** ScoringRulesOut */
    ScoringRulesOut: {
      /** Points */
      points: {
        [key: string]: number;
      };
    };
    /** Season */
    Season: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Number */
      number: number;
    };
    /** SeasonIn */
    SeasonIn: {
      /** Name */
      name: string;
      /** Number */
      number: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  my_leagues_leagues_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueOut"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  create_league_leagues_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  get_league_leagues__league_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  update_league_leagues__league_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  get_leaderboard_leagues__league_id__leaderboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeaderboardEntryOut"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  list_members_leagues__league_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueMember"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  join_league_leagues__league_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinLeagueIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueMember"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  my_membership_leagues__league_id__members_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueMember"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  set_my_roster_leagues__league_id__members_me_roster_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RosterIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueMember"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  league_scoring_rules_leagues__league_id__scoring_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScoringRulesOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  me_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  scoring_rules_scoring_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScoringRulesOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  list_seasons_seasons_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  get_season_seasons__season_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  upsert_season_seasons__season_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SeasonIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Season"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  list_contestants_seasons__season_id__contestants_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contestant"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  upsert_contestant_seasons__season_id__contestants__contestant_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        contestant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContestantIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contestant"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  list_episode_stats_seasons__season_id__episodes__episode__stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        episode: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  record_stat_seasons__season_id__episodes__episode__stats__contestant_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
        episode: number;
        contestant_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EpisodeStatIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  contestant_points_seasons__season_id__points_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContestantPointsOut"];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
  list_season_stats_seasons__season_id__stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        season_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStat"][];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not allowed for this user */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description League rule violated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Authentication not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorOut"];
        };
      };
    };
  };
}
